### ISSUE TITLE
Cannot read property 'entities' of undefined

### ISSUE THREAD

**Issue by BjornMelgaard** [mschipperheyn/normalizr-immutable#18]
`projects.toString() // from "state.projects", Map instance`
 and many other functions throw this error (eg `ownProps.project.tasks.includes(taskId)` [there](https://github.com/BjornMelgaard/react-test/blob/64c42833905f7022b58c6eede4977660c3dc1bb9/app/assets/javascripts/modules/task/components/TaskList.js#L12))

I saw you redefined many functions from `immutable`, maybe this is the source

**Comment by mschipperheyn** [comment]
Can you provide some more code for me to understand. And which version are you using?

**Comment by BjornMelgaard** [comment]
Sorry, I move from `normalizr-immutable` to vanilla `Immutable.fromJS` for better handleability.
But there is [commit of this issue](https://github.com/BjornMelgaard/react-test/tree/64c42833905f7022b58c6eede4977660c3dc1bb9) 

I think origin of this issue is that initialState of project reducer is Map({}) [there](https://github.com/BjornMelgaard/react-test/blob/64c42833905f7022b58c6eede4977660c3dc1bb9/app/assets/javascripts/ProjectRoot.js) 
```
import { Map } from "immutable"
import * as types from "../projectConstants"

const initialState = Map({})

export default function projects(state = initialState, action = {}) {
  switch (action.type) {
  case types.LOAD_PROJECTS: {
    return state.merge(action.payload)
  }
  default:
    return state
  }
}

```

And then I marge it like this `  dispatch(loadProjects(normalized.entities.projects))`

And when I try use it `state.projects.toString()`, it throw `Cannot read property 'entities' of undefined` error

**Comment by mschipperheyn** [comment]
Ok, at a glance, it seems to me that you should merge entities and not entities.projects. 

Also, "property 'entitities' of undefined" suggests that the projectsReducer is not available when that call is made. This could be related to not supplying the reducer reference correctly in the schema definition.

**Comment by BjornMelgaard** [comment]
Yes, or I had to use NormalizedRecord as initialState, I just surprised that entities created by "normalizr-immutable" is not compatible with vanilla immutable entities at first glance, I will close the issue, thanks you for your time

P.S. I thought that Record doesn`t have Iterable methods, I was misguided by official documentation :smile:

**Comment by mschipperheyn** [comment]
The entities created by normalizr-immutable are simple immutable Records, fully compatible. If you start using the Proxy facilities, you have to take a little more care in how you use things. But for me, the pains are worth it.

One more thing: I recommed using the latest 0.0.4 beta of normalize-immutable. Depending on configuration the 0.0.3 branch uses a Record for the entities structure which was a misguided choice on my part.

**Comment by BjornMelgaard** [comment]
Ok, currently I just teaching react, it seems I will return to `normalizr-immutable` once)
