### ISSUE TITLE
Unable to import from 'normalizr-immutable'

### ISSUE THREAD

**Issue by tryggvigy** [mschipperheyn/normalizr-immutable#3]
After a normal `npm install` I was unable to import anything from the library.
I am unfamiliar with publishing libraries like this so I'm probably wrong, but could this be due to 
no `index.js` being present for this library? I see no `index.js` in the `src` folder.

**Comment by mschipperheyn** [comment]
Hmm, I'm also new to the process of publishing on npm. I installed it and it worked for me, but you could be right. I'll investigate.

**Comment by mschipperheyn** [comment]
Yeah, you were right. Sorry about that. I released a 0.0.2 that should fix that issue

**Comment by tryggvigy** [comment]
Awesome. Thanks for looking into this. 👍
