### ISSUE TITLE
reducer key per schema?

### ISSUE THREAD

**Issue by babsonmatt** [mschipperheyn/normalizr-immutable#5]
Any thoughts on allowing reducerKey to be defined on a per schema basis to support proxying across reducers?

**Comment by mschipperheyn** [comment]
I haven't thought about that, no. It's an interesting idea, given the fact that many objects are common across reducers.

**Comment by mschipperheyn** [comment]
I'm just thinking that its challenging because if you'rr reading from the json initially,you would end up having to seed multiple reducers w the result of the normalization. Because otherwise you might be referencing a reducer object that hasn't been seeded yet. Any thoughts?

**Comment by babsonmatt** [comment]
With my personal setup I have 1 reducer per 'entity', so users, posts, etc. so it would definitely be beneficial to be able to configure things to look at different reducers (since without it I can't really use Proxy support in its current form, haha).

So I guess I'm doing what you're describing, with seeding multiple reducers with the result of a single normalizr result... I haven't had any issues that I'm aware of... just multiple reducers each 'listening' to the particular actions and only processing the part of the normalized data they're concerned with.

**Edit**: Just realized what you were saying, I currently use reselect to de-normalize my normalizr data back from the reducers into it's original form for me to use within React and definitely have to wait to make sure I have everything...hmm... is it a big issue if a reducer isnt seeded when someone attempts to access it?  Would being sure all the data was in place before attempting to use it be out of scope for this lib?

**Comment by mschipperheyn** [comment]
Ok, yeah I suppose it's possible if you make sure that all reducers are
updated with the normalization result. There are some issues in the case
that the data. For an entity that come s back across various actions is not
always equal. For instance,  a user with varying kinds of content detail
depending on the rest endpoint. Also this would make the solution much more
redux centric. But I like the idea. If there are some +1s?

On Tue, May 10, 2016, 22:09 Matt notifications@github.com wrote:

> With my personal setup I have 1 reducer per 'entity', so users, posts,
> etc. so it would definitely be beneficial to be able to configure things to
> look at different reducers (since without it I can't really use Proxy
> support in its current form, haha).
> 
> So I guess I'm doing what you're describing, with seeding multiple
> reducers with the result of a single normalizr result... I haven't had any
> issues that I'm aware of... just multiple reducers each 'listening' to the
> particular actions and only processing the part of the normalized data
> they're concerned with.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/mschipperheyn/normalizr-immutable/issues/5#issuecomment-218336506
> 
> ## 
> 
> Kind regards,

Marc
M.Schipperheyn

**Comment by mschipperheyn** [comment]
The one you walk into when you add reducerKey to the Schema is that you may have to start maintaining multiple copies of the same Record if you _don't_ want this "cross-reducer" behaviour. For instance, if you use a User Schema across multiple reducers.

**Comment by babsonmatt** [comment]
@mschipperheyn is there a reason to have multiple 'users' per reducer?  I was under the impression you only want one, and then you'd just reference the main user reducer by id from other reducers.

**Comment by mschipperheyn** [comment]
Well, it really depends on your preference. You can normalize your entities across reducers, but a simpler solution would be to just maintain duplicates across reducers depending on its purpose. You might have a more slimmed down version of a user object in one reducer and a more extensive one in another.

So, it's really a question of: do we apply this use case with a reducerKey per Schema, possibly requiring duplication of schema definitions, or do we keep it the way it is. I suppose the use case you suggest offers more flexibility, so I think we should accept possible duplication.

**Comment by mschipperheyn** [comment]
Ok, implemented
